// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace lecture_9
{
    [Table("tblDrugs")]
    [Index(nameof(DrugName), nameof(DoseMg), Name = "NonClusteredIndex-20210428-004939", IsUnique = true)]
    public partial class TblDrugs
    {
        public TblDrugs()
        {
            TblPrescriptions = new HashSet<TblPrescriptions>();
        }

        [Key]
        public int DrugId { get; set; }
        [Column("Dose_MG", TypeName = "decimal(10, 2)")]
        public decimal DoseMg { get; set; }
        [Required]
        [StringLength(200)]
        public string DrugName { get; set; }

        [InverseProperty("Drug")]
        public virtual ICollection<TblPrescriptions> TblPrescriptions { get; set; }
    }
}