// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace lecture_9
{
    [Table("tblPrescriptions")]
    public partial class TblPrescriptions
    {
        [Key]
        public int TreatmentId { get; set; }
        [Key]
        public int DrugId { get; set; }

        [ForeignKey(nameof(DrugId))]
        [InverseProperty(nameof(TblDrugs.TblPrescriptions))]
        public virtual TblDrugs Drug { get; set; }
        [ForeignKey(nameof(TreatmentId))]
        [InverseProperty(nameof(TblTreatments.TblPrescriptions))]
        public virtual TblTreatments Treatment { get; set; }
    }
}