// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace lecture_9
{
    [Table("tblUserTypes")]
    public partial class TblUserTypes
    {
        public TblUserTypes()
        {
            TblUsers = new HashSet<TblUsers>();
        }

        [Key]
        public byte UserTypeId { get; set; }
        [Required]
        [StringLength(150)]
        public string UserTypeName { get; set; }

        [InverseProperty("UserTypeNavigation")]
        public virtual ICollection<TblUsers> TblUsers { get; set; }
    }
}