// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace lecture_3
{
    [Table("tblStudents")]
    public partial class TblStudents
    {
        public int StudentId { get; set; }
        [Required]
        [StringLength(200)]
        public string StudentName { get; set; }
        [Required]
        [StringLength(2200)]
        public string StudentEmail { get; set; }
        public bool IsMale { get; set; }
        [StringLength(250)]
        public string NickName { get; set; }
        [Key]
        public int UniqueId { get; set; }
    }
}