// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace lecture_6
{
    [Table("tblDrugs")]
    public partial class TblDrugs
    {
        public TblDrugs()
        {
            TblPrescriptions = new HashSet<TblPrescriptions>();
        }

        [Key]
        public int DrugId { get; set; }
        [Column("Dose_MG")]
        public short DoseMg { get; set; }
        [Required]
        [StringLength(200)]
        public string DrugName { get; set; }

        [InverseProperty("Drug")]
        public virtual ICollection<TblPrescriptions> TblPrescriptions { get; set; }
    }
}